name: "Bug Report"
description: "Report a bug in MassOS"
title: "[Bug]: "
labels: "bug"
body:
- type: "checkboxes"
  attributes:
    label: "Checklist"
    description: "Please make sure you have read the following."
    options:
      - label: "I have searched for [other issues](https://www.github.com/MassOS-Linux/MassOS/issues), and can confirm my issue has not already been reported."
        required: true
      - label: "I have read and understood, and agree to abide by, the [MassOS Project Code of Conduct](https://github.com/MassOS-Linux/MassOS/blob/development/CODE_OF_CONDUCT.md)."
        required: true
- type: "input"
  attributes:
    label: "MassOS version"
    description: "What version of MassOS are you using? Run `massos-release` in a terminal if unsure. Note that we no longer accept bug reports for MassOS 2022.10 or older."
    placeholder: "experimental-20251016"
  validations:
    required: true
- type: "input"
  attributes:
    label: "Kernel version"
    description: "What is the output of `uname -srvm` in a terminal? You may skip this question if your issue is related to booting MassOS in the first place."
    placeholder: "Linux 6.17.3-massos #1 SMP PREEMPT_DYNAMIC Thu Oct 16 22:59:17 UTC 2025 x86_64"
  validations:
    required: false
- type: "checkboxes"
  attributes:
    label: "Subject"
    description: "Which of the following best describes your issue (multiple responses are OK)?"
    options:
      - label: "Issue with the MassOS Live CD and/or installing MassOS."
      - label: "Issue with a particular piece of software in MassOS."
      - label: "Issue with booting or startup of MassOS."
      - label: "Issue with hardware or peripherals on MassOS."
      - label: "Issue with upgrading MassOS."
      - label: "Issue with the MassOS documentation."
      - label: "Issue with compiling MassOS from source."
      - label: "Other issue (please describe in detail below)."
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Expected Behavior"
    description: "A clear description of what you expected to happen."
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Actual Behavior"
    description: "A clear description of what actually happened."
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Steps to Reproduce"
    description: "A clear description of how to reproduce the problem."
    placeholder: "Open `...`, click on `...`, select `...`, see error."
  validations:
    required: false
- type: "textarea"
  attributes:
    label: "Hardware Information"
    description: "Please include as much information about your hardware as possible, such as CPU, GPU and System Model / Motherboard. If you are using a VM, please state the virtualization software used as well as the VM's configuration."
  validations:
    required: false
- type: "textarea"
  attributes:
    label: "Additional Information or Context"
    description: "If desired, you can provide additional information about, or context for, your issue, if you feel it will be useful for solving/debugging."
  validations:
    required: false
