name: "Feature Request"
description: "Request a feature for MassOS."
title: "[Feature Request]: "
labels: "feature request"
body:
- type: "checkboxes"
  attributes:
    label: "Checklist"
    description: "Please make sure you have read the following."
    options:
      - label: "I have searched for [other issues](https://www.github.com/MassOS-Linux/MassOS/issues), and can confirm my feature request has not already been reported."
        required: true
- type: "textarea"
  attributes:
    label: "Suggestion"
    description: "A clear description of what you would like to see in a future release of MassOS, and an explanation of how it would benefit the project and/or users."
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Licensing implications"
    description: "Please describe any licensing implications of adding your requested feature, for example, if you are suggesting a piece of software which is not GPL-compatible. Leave this field empty if not applicable."
  validations:
    required: false
