OSINSTALLGUI_ROOTFS="/run/initramfs/squashed.img"
OSINSTALLGUI_ROOTFS_ALT="/run/initramfs/live/LiveOS/squashfs.img"
OSINSTALLGUI_CLEANUP_CMD="/tmp/livecd-cleanup.sh"
OSINSTALLGUI_INITRAMFS_CMD="/usr/bin/mkinitramfs"
OSINSTALLGUI_ALLOW_BTRFS=1
OSINSTALLGUI_LOCALES_CMD="/usr/bin/mklocales"
OSINSTALLGUI_LOCALES_FILE="/etc/locales"
OSINSTALLGUI_KEYMAPS_SYSTEMD=1
OSINSTALLGUI_KEYMAPS_LOCATION="/usr/share/keymaps"
OSINSTALLGUI_ROOTPW=1
OSINSTALLGUI_ADMIN_GROUP="wheel,lpadmin"
OSINSTALLGUI_USER_SHELL="/usr/bin/bash"
OSINSTALLGUI_USER_PWSCORE=0
