OSINSTALLGUI_ROOTFS="/run/initramfs/squashed.img"
OSINSTALLGUI_ROOTFS_ALT="/run/initramfs/live/LiveOS/squashfs.img"
OSINSTALLGUI_CLEANUP_CMD="/tmp/livecd-cleanup.sh"
OSINSTALLGUI_INITRAMFS_CMD="/usr/bin/mkinitramfs"
OSINSTALLGUI_ALLOW_BTRFS=1
OSINSTALLGUI_ALLOW_LUKS=1
OSINSTALLGUI_LUKS_MAPPER_NAME="cryptroot"
OSINSTALLGUI_LUKS_ARGON2=1
OSINSTALLGUI_ALWAYS_OFFER_FULLPORT=0
OSINSTALLGUI_LOCALES_CMD="/usr/bin/mklocales"
OSINSTALLGUI_LOCALES_FILE="/etc/locales"
OSINSTALLGUI_KEYMAPS_SYSTEMD=1
OSINSTALLGUI_KEYMAPS_LOCATION="/usr/share/keymaps"
OSINSTALLGUI_ROOTPW=1
OSINSTALLGUI_ADMIN_GROUP="wheel,lpadmin"
OSINSTALLGUI_USER_SHELL="/usr/bin/bash"
OSINSTALLGUI_USER_PWSCORE=0
OSINSTALLGUI_GRUB_EXTRA_ARGS_LEGACY=""
OSINSTALLGUI_GRUB_EXTRA_ARGS_UEFIIN=""
OSINSTALLGUI_GRUB_EXTRA_ARGS_UEFIRM=""
