.TH "MASSOS-SNAPD" "8" "October 2025" "massos-snapd" "MassOS System Utilities"
.hy
.SH NAME
.PP
massos-snapd - Utility to manage the Snapd installation on a MassOS system.
.SH SYNOPSIS
.PP
\f[B]massos-snapd\f[R] <\f[I]install\f[R]|\f[I]uninstall\f[R]|\f[I]status\f[R]>
.SH DESCRIPTION
.PP
\f[B]massos-snapd\f[R] is a utility to manage the installation of the Snapd package manager on a MassOS system.

\f[B]massos-snapd\f[R] can install and uninstall Snapd, as well as check and report the installed status of Snapd.

Snapd is not installed by default, due to its controversy. It is disliked by many users for a variety of (justified) reasons. However, it can provide easy access to some packages which are not otherwise available on MassOS, and are not available through flatpak(1). It is therefore beneficial to make Snapd available to any users of MassOS who may want or need to use it.

\f[B]massos-snapd\f[R] accesses the file <\f[I]/usr/share/massos/snapdversion\f[R]>, which contains information about the version of Snapd corresponding to the MassOS version. It uses this file to determine which Snapd version to install. The file can also be used to inform the utility of an available update to the Snapd version (e.g., after a MassOS system upgrade).

Be aware that a system restart will be required after installing or uninstalling Snapd. Note also that this utility is incompatible with (older) versions of MassOS which lack the <\f[I]/usr/share/massos/snapdversion\f[R]> file or use a split bin-sbin filesystem structure.

After installing Snapd, you can optionally install the "App Center" (previously known as "Snap Store") to provide a graphical user interface to install and manage Snap applications. Install it by running the command \f[B]snap install snap-store\f[R].
.SH EXIT STATUS
.PP
\f[B]massos-snapd\f[R] will exit with 0 for success and >0 for failure.
.SH EXAMPLES
.TP
\f[B]massos-snapd status\f[R]
Check whether or not Snapd is installed on the system.
.TP
\f[B]massos-snapd install\f[R]
Install, update, or reinstall Snapd onto the system.
.TP
\f[B]massos-snapd uninstall\f[R]
Uninstall Snapd from the system.
.SH SEE ALSO
.TP
snap(8), flatpak(1)
.SH BUGS
.PP
Report bugs to <https://github.com/MassOS-Linux/MassOS/issues>.
.SH COPYRIGHT
.PP
Copyright (C) 2025 Daniel Massey.

This software is part of the MassOS system, and is licensed under the GNU GPLv3+.

A copy of the license can be found at </usr/share/massos/LICENSE> on a MassOS system. It can also be found online at <https://www.gnu.org/licenses/gpl.html>.
