.TH "MASSOS-RELEASE" "1" "May 2022" "massos-release" "MassOS System Utilities"
.hy
.SH NAME
.PP
massos-release - Display the installed version of MassOS.
.SH SYNOPSIS
.PP
\f[B]massos-release\f[R]
.SH DESCRIPTION
.PP
\f[B]massos-release\f[R] is a simple utility that will display the installed version of MassOS (e.g. 2022.06) on standard output. It is human-readable and machine-parseable.

\f[B]massos-release\f[R] reads the /etc/massos-release file, which should contain a single line stating the MassOS release. If this file doesn't exist, the program will return an error instead,

On development branch builds, "development" is returned instead of a release version. In this case you may wish to use uname(1) to check the kernel build date instead.
.SH EXIT STATUS
.PP
\f[B]massos-release\f[R] will exit with 0 for success and 1 for failure.
.SH EXAMPLES
.TP
\f[B]massos-release\f[R]
Returns the currently installed version of MassOS.
.SH SEE ALSO
.TP
uname(1)
.SH BUGS
.PP
Report bugs to <https://github.com/MassOS-Linux/MassOS/issues>.

NOTE: Please first check that your issue has not yet been fixed in the development branch!
.SH COPYRIGHT
.PP
Copyright (C) 2022 MassOS Developers.

This software is part of the MassOS system, and is licensed under the GNU GPLv3+.

A copy of the license can be found at /usr/share/massos/LICENSE on a MassOS system.

It can also be found at <https://www.gnu.org/licenses/gpl.html>.
