#!/usr/bin/env bash

# massos-snapd - Utility to manage the Snapd installation on a MassOS system.
# Copyright (C) 2025 Daniel Massey. Licensed under GPLv3+.

# shellcheck disable=SC2155

# Exit on error.
set -e

# Set the software version.
ver="0.0.7"

# Version of Go. Shouldn't really need to be updated frequently.
ver_go="1.26.0"
sum_go="aac1b08a0fb0c4e0a7c1555beb7b59180b05dfc5a3d62e40e9de90cd42f88235"
sum_goarm="bd03b743eb6eb4193ea3c3fd3956546bf0e3ca5b7076c8226334afe6b75704cd"

# What is our name?
inv="$(basename "$0")"

# What is the MassOS release?

# Message functions.
die() {
  # Red text and exit unsuccessfully.
  echo -e "\e[1;31mERROR: $*\e[0m" >&2
  exit 1
}
msg() {
  # Yellow text.
  echo -e "\e[1;33m$*\e[0m"
}
suc() {
  # Green text.
  echo -e "\e[1;32m$*\e[0m"
}

# Prompt.
prompt() {
  # Yellow text.
  printf '\e[1m%s [y/N]\e[0m ' "$*"
  read -r ans
  # Return depending on what was specified.
  case "$ans" in
    y|Y|yes|Yes|yEs|yeS|YEs|YeS|yES|YES) return 0 ;;
    *) return 1 ;;
  esac
}

# Ensure we are running as root.
if test $EUID -ne 0; then
  die "This utility must be run as root (use 'sudo')."
fi

# Obtain the version of MassOS we are running on.
ver_massos="$(cat /etc/massos-release 2>/dev/null || echo "UNKNOWN")"

# Determine the version of snapd as defined by the MassOS build.
ver_snapd="$(grep -sm1 "^version:" /usr/share/massos/snapdversion | cut -d' ' -f2)"
sum_snapd="$(grep -sm1 "^checksum:" /usr/share/massos/snapdversion | cut -d' ' -f2)"

# We can only run if a version was successfully determined.
if test -z "$ver_snapd"; then
  die "This utility is only supported on a newer version of MassOS."
fi

# We no longer support split bin-sbin in MassOS.
if ! readlink /usr/sbin &>/dev/null; then
  die "This utility is only supported on a newer version of MassOS."
fi

# Determine the installed status of snapd.
installed_snapd=""
if snap version &>/dev/null; then
  installed_snapd="$(snap version 2>/dev/null | head -n1 | xargs | cut -d' ' -f2)"
fi

# Determin

# Display usage function.
usage() {
  echo "$inv (MassOS Snapd Installation Manager) $ver"
  echo "Dealing with Snapd $ver_snapd for MassOS $ver_massos."
  echo
  echo "Usage: $inv <operation>"
  echo
  echo "Supported operations:"
  echo
  echo "  $inv install   - Install (or update) Snapd on your system."
  echo "  $inv uninstall - Uninstall Snapd from your system."
  echo "  $inv status    - Check if Snapd is installed on your system."
  echo
  echo "For more extensive documentation, see 'man $inv'."
  echo
  echo "Copyright (C) 2025 Daniel Massey."
  echo "This utility is free software, licensed under the GNU GPLv3+ license."
  echo "See the file </usr/share/massos/LICENSE> for more information."
  echo "The license and copright on Snapd is unaffected by this utility."
  echo "This utility's authors make no additional copyright claims over Snapd."
}

# Install function.
operation_install() {
  # Check if we are up-to-date first.
  if test ! -z "$installed_snapd"; then
    if test "$installed_snapd" = "$ver_snapd"; then
      msg "Snapd is already installed ($ver_snapd). It will be reinstalled."
    else
      msg "Snapd will be updated from $installed_snapd to $ver_snapd."
    fi
  else
    msg "Snapd $ver_snapd will be installed on your system."
  fi
  # Confirmation prompt.
  if ! prompt "Do you want to proceed with this operation?"; then
    die "Operation will not proceed at user's discretion."
  fi
  # Set up a working directory.
  workdir="$(mktemp -d "/tmp/$inv-XXXXXX")"
  pushd "$workdir" >/dev/null
  # Download stuff.
  msg "Downloading source files..."
  curl -fL "https://dl.google.com/go/go$ver_go.linux-amd64.tar.gz" -o dl_go
  curl -fL "https://dl.google.com/go/go$ver_go.linux-arm64.tar.gz" -o dl_goarm
  curl -fL "https://github.com/canonical/snapd/releases/download/$ver_snapd/snapd_$ver_snapd.vendor.tar.xz" -o dl_snapd
  # Verify stuff.
  echo "$sum_go dl_go" | sha256sum -c
  echo "$sum_goarm dl_goarm" | sha256sum -c
  echo "$sum_snapd dl_snapd" | sha256sum -c
  # Extract stuff.
  msg "Extracting source files..."
  install -d go goroot snapd
  if test "$(uname -m)" = "x86_64"; then
    tar -xf dl_go -C goroot --strip-components=1
  elif test "$(uname -m)" = "aarch64"; then
    tar -xf dl_goarm -C goroot --strip-components=1
  else
    die "Unsupported architecture. Cannot continue."
  fi
  tar -xf dl_snapd -C snapd --strip-components=1
  # Build the thing.
  msg "Building Snapd $ver_snapd..."
  # Set up the environment variables for the build.
  unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
  unset CGO_CFLAGS CGO_CXXFLAGS CGO_CPPFLAGS CGO_LDFLAGS
  export PATH="$PWD/goroot/bin:$PATH"
  export GOPATH="$PWD/go"
  export GO111MODULE=off
  export CGO_ENABLED=1
  export MAKEFLAGS="-j$(nproc)"
  # Make Go use our source instead of re-downloading.
  install -dm755 go/src/github.com/snapcore
  ln -sfr snapd go/src/github.com/snapcore/snapd
  # Parepare Snapd sources.
  pushd snapd >/dev/null
  ./mkversion.sh "$ver_snapd" 2>/dev/null
  # Build dyanmic Go components of Snapd.
  go build -trimpath -buildmode=pie -ldflags="-linkmode=external" -o "$GOPATH"/bin/snap -tags nomanagers "github.com/snapcore/snapd/cmd/snap"
  go build -trimpath -buildmode=pie -ldflags="-linkmode=external" -o "$GOPATH"/bin/snapd "github.com/snapcore/snapd/cmd/snapd"
  go build -trimpath -buildmode=pie -ldflags="-linkmode=external" -o "$GOPATH"/bin/snapd-apparmor "github.com/snapcore/snapd/cmd/snapd-apparmor"
  go build -trimpath -buildmode=pie -ldflags="-linkmode=external" -o "$GOPATH"/bin/snap-seccomp "github.com/snapcore/snapd/cmd/snap-seccomp"
  go build -trimpath -buildmode=pie -ldflags="-linkmode=external" -o "$GOPATH"/bin/snap-failure "github.com/snapcore/snapd/cmd/snap-failure"
  # Build static Go components of Snapd.
  go build -trimpath -buildmode=exe -ldflags="-linkmode=external -extldflags='-static'" -o "$GOPATH"/bin/snap-update-ns "github.com/snapcore/snapd/cmd/snap-update-ns"
  go build -trimpath -buildmode=exe -ldflags="-linkmode=external -extldflags='-static'" -o "$GOPATH"/bin/snap-exec "github.com/snapcore/snapd/cmd/snap-exec"
  go build -trimpath -buildmode=exe -ldflags="-linkmode=external -extldflags='-static'" -o "$GOPATH"/bin/snapctl "github.com/snapcore/snapd/cmd/snapctl"
  # Build data files of Snapd.
  make -C data BINDIR=/usr/bin LIBEXECDIR=/usr/lib SNAPD_ENVIRONMENT_FILE=/etc/default/snapd SYSTEMDSYSTEMUNITDIR=/usr/lib/systemd/system
  # Build C/C++ components of Snapd.
  pushd cmd >/dev/null
  autoreconf -fi
  ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libexecdir=/usr/lib/snapd --enable-apparmor --enable-merged-usr --enable-nvidia-biarch
  make
  popd >/dev/null
  # Install Snapd and its data.
  msg "Installing Snapd $ver_snapd..."
  install -t /usr/bin -Dm755 "$GOPATH"/bin/snap
  install -t /usr/lib/snapd -Dm755 "$GOPATH"/bin/snap{ctl,d{,-apparmor},-exec,-failure,-seccomp,-update-ns}
  ln -sfr /usr/lib/snapd/snapctl /usr/bin/snapctl
  install -dm755 /snap
  install -dm755 /var/cache/snapd
  install -dm755 /var/lib/snapd/{apparmor,assertions,dbus-1/services,dbus-1/system-services,desktop/applications,device,hostfs,inhibit,lib/gl,lib/gl32,lib/vulkan,lib/glvnd,mount,seccomp/bpf,snaps}
  install -dm700 /var/lib/snapd/{cache,cookie}
  make -C cmd install
  install -t /usr/share/bash-completion/completions -Dm644 data/completion/bash/snap
  install -t /usr/lib/snapd -Dm644 data/completion/bash/{complete,etelpmoc}.sh
  make -C data DBUSSERVICESDIR=/usr/share/dbus-1/services SYSTEMDSYSTEMUNITDIR=/usr/lib/systemd/system install
  install -t /usr/share/polkit-1/actions -Dm644 data/polkit/io.snapcraft.snapd.policy
  install -dm755 /usr/share/man/man8
  /usr/bin/snap help --man > /usr/share/man/man8/snap.8
  install -t /usr/lib/snapd -Dm644 data/info
  gzip -9f /usr/share/man/man8/snap.8
  gzip -9f /usr/share/man/man8/snap-confine.8
  gzip -9f /usr/share/man/man8/snap-discard-ns.8
  gzip -9f /usr/share/man/man8/snapd-env-generator.8
  rm -f /usr/lib/systemd/system/snapd.{system-shutdown.service,autoimport.service,recovery-chooser-trigger.service,core-fixup.*,snap-repair.*}
  rm -f /usr/lib/snapd/{snapd.core-fixup.sh,system-shutdown}
  rm -f /usr/bin/ubuntu-core-launcher
  install -t /usr/share/licenses/snapd -Dm644 COPYING
  # Strip the executables.
  msg "Stripping executables..."
  strip --strip-unneeded /usr/bin/snap 2>/dev/null || true
  strip --strip-unneeded /usr/lib/snapd/* 2>/dev/null || true
  # Enable Snapd systemd services.
  msg "Enabling Snapd systemd services..."
  setcap -q - /usr/lib/snapd/snap-confine < /usr/lib/snapd/snap-confine.caps
  update-desktop-database
  systemctl daemon-reload
  systemctl enable snapd
  systemctl enable snapd.apparmor
  # Clean up.
  msg "Cleaning up..."
  popd >/dev/null
  popd >/dev/null
  rm -rf "$workdir"
  # Display successful finishing message and restart prompt.
  suc "Snapd $ver_snapd has been successfully installed."
  if prompt "Your system will now reboot. Is this OK?"; then
    shutdown -r now
  else
    die "You MUST manually reboot the system before attempting to use Snapd."
  fi
}

# Uninstall function.
operation_uninstall() {
  # We cannot uninstall it if it is already not installed.
  if test -z "$installed_snapd"; then
    die "Snapd is already not installed. Nothing to uninstall."
  fi
  msg "Snapd $ver_snapd will be uninstalled from your system."
  # Confirmation prompt.
  if ! prompt "Do you want to proceed with this operation?"; then
    die "Operation will not proceed at user's discretion."
  fi
  # TODO: Implement this functionality.
  die "This functionality is not yet implemented, sorry!"
}

# Status function.
operation_status() {
  if test ! -z "$installed_snapd"; then
    # Snapd is installed.
    if test "$installed_snapd" = "$ver_snapd"; then
      # Snapd is up-to-date.
      msg "Snapd $installed_snapd is installed and up-to-date."
    else
      # Snapd is outdated.
      msg "Snapd $installed_snapd is installed, but outdated by $ver_snapd."
      msg "Run '$inv install' to upgrade the Snapd installation to $ver_snapd."
    fi
  else
    msg "Snapd is not installed. Run '$inv install' to install $ver_snapd."
  fi
}

# Determine what to do based on which operation was specified.
operation="$1"
shift || true
case "$operation" in
  install) operation_install ;;
  uninstall) operation_uninstall ;;
  status) operation_status ;;
  help|-h|-help|--help) usage ;;
  version|-v|-V|-version|--version) usage | head -n2; usage | tail -n6 ;;
  *) usage >&2; exit 1 ;;
esac
