#!/usr/bin/env bash

# mbs - MassOS Build System Utility
# This utility is designed to wrap around common build systems of packages.

# Copyright (C) 2025 Daniel Massey

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck disable=SC2086,SC2155

# What is our name?
export MBS_INV="$(basename "$0")"

# What is our version and copyright year?
export MBS_VER="0.0.1"
export MBS_YEAR="2025"

# What is the MassOS version?
export MBS_HOST_VER="$(cat /etc/massos-release 2>/dev/null || echo "UNKNOWN")"

# Set up default compiler options if they are not specified.
test ! -z "$CFLAGS" || export CFLAGS="-Os"
test ! -z "$CXXFLAGS" || export CXXFLAGS="-Os"

# Set up common flags only if they are unset in the environment.
test ! -z "$MBS_FLAGS_CONFIGURE" || export MBS_FLAGS_CONFIGURE="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --runstatedir=/run --bindir=/usr/bin --libdir=/usr/lib --sbindir=/usr/bin --mandir=/usr/share/man"
test ! -z "$MBS_FLAGS_MESON" || export MBS_FLAGS_MESON="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --sbindir=bin --buildtype=minsize"
test ! -z "$MBS_FLAGS_CMAKE" || export MBS_FLAGS_CMAKE="-DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=MinSizeRel"

# Unset all flags if MBS_FLAGS_NODEFAULTS=YES
test "$MBS_FLAGS_NODEFAULTS" != "YES" || export MBS_FLAGS_CONFIGURE="" MBS_FLAGS_MESON="" MBS_FLAGS_CMAKE=""

# Parallel build by default, unless otherwise specified.
test ! -z "$MAKEFLAGS" || export MAKEFLAGS="-j$(nproc)"

# Display message function.
mbs_msg() {
  echo -e "\e[1;33m$MBS_INV: $*\e[0m"
}

# Display success function.
mbs_suc() {
  echo -e "\e[1;32m$MBS_INV: $*\e[0m"
}


# Exit on error function.
mbs_die() {
  echo -e "\e[1;31m$MBS_INV: $* Aborting...\e[0m" >&2
  exit 1
}

# Usage function.
mbs_usage() {
  echo "$MBS_INV (MassOS Build System Utility) $MBS_VER (MassOS $MBS_HOST_VER)"
  echo "Copyright (C) 2025 Daniel Massey / MassOS Developers"
  echo "Licensed under GNU GPLv3+; see '/usr/share/massos/LICENSE'."
  echo
  echo "Usage: mbs <command> [options]"
  echo
  echo "Available commands:"
  echo
  echo "  $MBS_INV extract   - Extract a source tarball."
  echo "  $MBS_INV apply     - Apply a patch file to the source tree."
  echo "  $MBS_INV configure - Build a project using a configure script."
  echo "  $MBS_INV meson     - Build a project using the Meson build system."
  echo "  $MBS_INV cmake     - Build a project using the CMake build system."
  echo "  $MBS_INV install   - Install a project after it has been built."
  echo "  $MBS_INV license   - Install one or more project license files."
  echo "  $MBS_INV cleanup   - Clean up the current directory."
  echo
  echo "For help with individual commands, try '$MBS_INV help <command>'."
  echo "For the full reference documentation, try 'man mbs'."
}

mbs_extract() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Set default extraction depth to 1 if unset.
  test ! -z "$MBS_EXTRACT_DEPTH" || MBS_EXTRACT_DEPTH=1
  # Locate file from current directory. Otherwise, check MBS_TARBALL_DIR.
  if test -z "$1"; then
    mbs_die "No tarball file name was specified."
  fi
  local tarball
  if test -e "$1"; then
    tarball="$1"
  elif test -e "$MBS_TARBALL_DIR/$1"; then
    tarball="$MBS_TARBALL_DIR/$1"
  else
    mbs_die "$1 was not found in the current directory or MBS_TARBALL_DIR."
  fi
  # Try to use bsdtar for extraction, since it supports more formats.
  local extractor
  if command -v bsdtar >/dev/null; then
    extractor=bsdtar
  elif command -v tar >/dev/null; then
    extractor=tar
  else
    mbs_die "No valid command for untarring was found on the system."
  fi
  # Extract the thing.
  "$extractor" -xf "$tarball" --strip-components="$MBS_EXTRACT_DEPTH"
  if test $? -ne 0; then
    mbs_die "Failed to untar $tarball (MBS_EXTRACT_DEPTH=$MBS_EXTRACT_DEPTH)."
  fi
  # It's done.
  mbs_suc "Successfully untarred $tarball (MBS_EXTRACT_DEPTH=$MBS_EXTRACT_DEPTH)."
}

mbs_apply() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Look for the specified patch file relative to here, and MBS_PATCH_DIR.
  # Also look for .patch and .diff filename endings, if not explicitly set.
  if test -z "$1"; then
    mbs_die "No patch file name was specified."
  fi
  local patchfile
  if test -e "$1"; then
    patchfile="$1"
  elif test -e "$1.patch"; then
    patchfile="$1.patch"
  elif test -e "$1.diff"; then
    patchfile="$1.diff"
  elif test -e "$MBS_PATCH_DIR/$1"; then
    patchfile="$MBS_PATCH_DIR/$1"
  elif test -e "$MBS_PATCH_DIR/$1.patch"; then
    patchfile="$MBS_PATCH_DIR/$1.patch"
  elif test -e "$MBS_PATCH_DIR/$1.diff"; then
    patchfile="$MBS_PATCH_DIR/$1.diff"
  else
    mbs_die "$1 was not found in the current directory or MBS_PATCH_DIR."
  fi
  # Apply the patch with specified patch depth, or 1 if unset.
  test ! -z "$MBS_PATCH_DEPTH" || MBS_PATCH_DEPTH=1
  mbs_msg "Applying $patchfile with a patch depth of $MBS_PATCH_DEPTH."
  patch -fNp"$MBS_PATCH_DEPTH" -i "$patchfile"
  if test $? -ne 0; then
    mbs_die "Failed to apply $patchfile (MBS_PATCH_DEPTH=$MBS_PATCH_DEPTH)."
  fi
  # It's done.
  mbs_suc "Successfully applied $patchfile (MBS_PATCH_DEPTH=$MBS_PATCH_DEPTH)."
}

mbs_configure() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  local confscript
  # Check if a configure script was specified, and if so, if it's valid.
  if test ! -z "$MBS_CONFIGURE_SCRIPT"; then
    if test -x "$MBS_CONFIGURE_SCRIPT"; then
      confscript="$MBS_CONFIGURE_SCRIPT"
    else
      # Exit on error with an appropriate message.
      mbs_die "Specified configure script $MBS_CONFIGURE_SCRIPT is not valid."
    fi
  fi
  # Look for configure scripts with various possible names.
  # TODO: Support configuring from a subdir (../configure) automatically.
  if test -z "$confscript"; then
    for cnf in {c,C}onfig{ure,}{,.sh}; do
      if test -x "$cnf"; then
        confscript="$cnf"
        break
      fi
    done
  fi
  # Ensure the directory has a configure script.
  if test -z "$confscript"; then
    # Exit and report that the configure script was not found.
    mbs_die "No valid configure was found, and MBS_CONFIGURE_SCRIPT is unset."
  fi
  # Run autoreconf if required.
  if test "$MBS_CONFIGURE_AUTORECONF" = "YES"; then
    mbs_msg "Running autoreconf to regenerate the configure script..."
    autoreconf -fi
    if test $? -ne 0; then
      mbs_die "Running autoreconf failed to regenerate the configure script."
    fi
  fi
  # Run the configure script.
  mbs_msg "Configuring the project with the configure script..."
  ./"$confscript" $MBS_FLAGS_CONFIGURE "$@"
  if test $? -ne 0; then
    mbs_die "The configure script failed to configure the project."
  fi
  # Exit immediately if make is disabled.
  if test "$MBS_CONFIGURE_NOMAKE" = "YES"; then
    mbs_suc "The project was successfully configured (make step disabled)."
    return
  fi
  # Ensure the configure script actually generated a Makefile.
  if test ! -e Makefile; then
    mbs_die "The configure script did not generate a Makefile."
  fi
  # Build the project.
  mbs_msg "Building the project using the generated Makefile..."
  make
  if test $? -ne 0; then
    mbs_die "The project failed to build using the generated Makefile."
  fi
  # It's done.
  mbs_suc "The project was successfully configured and built."
}

mbs_meson() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Ensure the directory has a meson.build file.
  if test ! -e meson.build; then
    mbs_die "No meson.build file exists in the current directory."
  fi
  # Ensure the directory does not have leftovers from a previous build.
  if test -e _mbsbuild; then
    mbs_die "Existing build cache was found. Remove the _mbsbuild directory."
  fi
  # Run the Meson build system.
  mbs_msg "Configuring the project with the Meson build system..."
  meson setup _mbsbuild $MBS_FLAGS_MESON "$@"
  if test $? -ne 0; then
    mbs_die "The Meson build system failed to configure the project."
  fi
  # Build the project.
  mbs_msg "Building the project using the Ninja build system..."
  ninja -C _mbsbuild
  if test $? -ne 0; then
    mbs_die "The project failed to build using the Ninja build system."
  fi
  # It's done.
  mbs_suc "The project was successfully configured and built."
}

mbs_cmake() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Ensure the directory has a CMakeLists.txt file.
  if test ! -e CMakeLists.txt; then
    mbs_die "No CMakeLists.txt file exists in the current directory."
  fi
  # Ensure the directory does not have leftovers from a previous build.
  if test -e _mbsbuild; then
    mbs_die "Existing build cache was found. Remove the _mbsbuild directory."
  fi
  # Run the CMake build system.
  mbs_msg "Configuring the project with the CMake build system..."
  cmake $MBS_FLAGS_CMAKE "$@" -Wno-dev -G Ninja -B _mbsbuild
  if test $? -ne 0; then
    mbs_die "The CMake build system failed to configure the project."
  fi
  # Build the project.
  mbs_msg "Building the project using the Ninja build system..."
  ninja -C _mbsbuild
  if test $? -ne 0; then
    mbs_die "The project failed to build using the Ninja build system."
  fi
  # It's done.
  mbs_suc "The project was successfully configured and built."
}

mbs_install() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Cannot run this if we are not root or DESTDIR is not set.
  if test -z "$DESTDIR" && test $EUID -ne 0; then
    mbs_die "Installing a project without DESTDIR requires root access."
  fi
  # Cannot install without DESTDIR if we are not the MassOS build system.
  if test -z "$DESTDIR" && test "$MBS_ALLOW_SYSINST" != "YES"; then
    mbs_die "Installing a project requires DESTDIR (or MBS_ALLOW_SYSINST=YES)."
  fi
  # Warn user if MBS_ALLOW_SYSINST=YES without MBS_HUSH_SYSINST_WARNING=YES.
  if test -z "$DESTDIR" && test "$MBS_HUSH_SYSINST_WARNING" != "YES"; then
    mbs_msg "WARNING! ALLOWING SYSTEM INSTALLATIONS MAY BREAK YOUR SYSTEM!"
  fi
  # Decide what to do depending on the build system type.
  if test -e _mbsbuild; then
    # Ninja build system (respects DESTDIR environment variable).
    mbs_msg "Installing the project using the Ninja build system..."
    ninja -C _mbsbuild -j1 install
    if test $? -ne 0; then
      mbs_die "The project failed to install using the Ninja build system."
    fi
  elif test -e Makefile; then
    # Generated Makefile (needs to manually pass DESTDIR arguments).
    mbs_msg "Installing the project using the generated Makefile..."
    make -j1 DESTDIR="$DESTDIR" install "$@"
    if test $? -ne 0; then
      mbs_die "The project failed to install using the generated Makefile."
    fi
  else
    # Nothing can be done.
    mbs_die "Neither the _mbsbuild directory nor a valid Makefile exists."
  fi
  # Finishing message.
  mbs_suc "The project was successfully installed."
}

mbs_license() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Cannot run this if we are not root or DESTDIR is not set.
  if test -z "$DESTDIR" && test $EUID -ne 0; then
    mbs_die "Installing license files without DESTDIR requires root access."
  fi
  # Capture package name and shift arguments.
  local licpkg="$(echo "$1" | tr '[:upper:]' '[:lower:]')"
  shift
  # Ensure the package name was specified.
  if test -z "$licpkg"; then
    mbs_die "You must specify the package name to install licenses for."
  fi
  # Ensure at least one license file was specified.
  if test -z "$*"; then
    mbs_die "You must specify at least one license file to install."
  fi
  # Ensure all the files are not not specified.
  for lic in "$@"; do
    if test ! -f "$lic"; then
      mbs_die "License file $lic does not exist."
    fi
  done
  # Install all license files.
  mbs_msg "Installing license files to $DESTDIR/usr/share/licenses/$licpkg..."
  install -vt "$DESTDIR"/usr/share/licenses/"$licpkg" -Dm644 "$@"
  if test $? -ne 0; then
    mbs_die "The license files failed to be installed successfully."
  fi
  # Finishing message.
  mbs_suc "The license files were successfully installed."
}

mbs_cleanup() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Do not run if we are in a dangerous directory.
  # Also require MBS_ALLOW_CLEANUP to be set.
  # This is for safety, since it will remove all files recursively.
  if test "$PWD" = "$HOME" || test "$PWD" = "/root" || test "$PWD" = "/"; then
    mbs_msg "WARNING! ALL FILES FROM CURRENT DIRECTORY WILL BE DELETED!"
    mbs_die "For safety, cleanup is not allowed in $PWD."
  fi
  if test "$MBS_ALLOW_CLEANUP" != "YES"; then
    mbs_msg "WARNING! ALL FILES FROM CURRENT DIRECTORY WILL BE DELETED!"
    mbs_die "For safety, cleanup is not allowed unless MBS_ALLOW_CLEANUP=YES."
  fi
  # Remove everything from the current directory.
  mbs_msg "Cleaning up the directory..."
  find . -mindepth 1 -delete
  mbs_suc "The directory was successfully cleaned up."
}

# Capture chosen command and shift arguments.
MBS_COMMAND="$(echo "$1" | tr '[:upper:]' '[:lower:]')"
shift

# Check how the program is run.
case "$MBS_COMMAND" in
  extract) mbs_extract "$@" ;;
  apply) mbs_apply "$@" ;;
  configure) mbs_configure "$@" ;;
  meson) mbs_meson "$@" ;;
  cmake) mbs_cmake "$@" ;;
  install) mbs_install "$@" ;;
  license) mbs_license "$@" ;;
  cleanup) mbs_cleanup "$@" ;;
  help|h|-h|-help|--help) mbs_usage ;;
  version|v|-v|-version|--version) mbs_usage | head -n3 ;;
  *) mbs_usage >&2; exit 1 ;;
esac
