#!/usr/bin/env bash

# mbs - MassOS Build System Utility
# This utility is designed to wrap around common build systems of packages.

# Copyright (C) 2025 Daniel Massey

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck disable=SC2086,SC2155

# What is our name?
export MBS_INV="$(basename "$0")"

# What is our version and copyright year?
export MBS_VER="0.1.0"
export MBS_YEAR="2025"

# What is the MassOS version?
export MBS_HOST_VER="$(cat /etc/massos-release 2>/dev/null || echo "UNKNOWN")"

# Set up default compiler options if they are not specified.
test ! -z "$CFLAGS" || export CFLAGS="-Os"
test ! -z "$CXXFLAGS" || export CXXFLAGS="-Os"
test ! -z "$LDFLAGS" || export LDFLAGS="-Wl,-O1"

# Set up default build types for Meson and CMake if unset.
test ! -z "$MBS_MESON_BT" || export MBS_MESON_BT="minsize"
test ! -z "$MBS_CMAKE_BT" || export MBS_CMAKE_BT="MinSizeRel"

# Set up common flags only if they are unset in the environment.
test ! -z "$MBS_FLAGS_CONFIGURE" || export MBS_FLAGS_CONFIGURE="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --runstatedir=/run --bindir=/usr/bin --libdir=/usr/lib --sbindir=/usr/bin --infodir=/usr/share/info --mandir=/usr/share/man"
test ! -z "$MBS_FLAGS_MESON" || export MBS_FLAGS_MESON="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --sbindir=bin --buildtype=$MBS_MESON_BT"
test ! -z "$MBS_FLAGS_CMAKE" || export MBS_FLAGS_CMAKE="-DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=$MBS_CMAKE_BT"

# Parallel build by default, unless otherwise specified.
test ! -z "$MAKEFLAGS" || export MAKEFLAGS="-j$(nproc)"

# Display message function.
mbs_msg() {
  echo -e "\e[1;33m$MBS_INV: $*\e[0m"
}

# Display success function.
mbs_suc() {
  echo -e "\e[1;32m$MBS_INV: $*\e[0m"
}

# Exit on error function.
mbs_die() {
  echo -e "\e[1;31m$MBS_INV: $* Aborting...\e[0m" >&2
  exit 1
}

# Usage function.
mbs_usage() {
  case "$1" in
    extract)
      echo "Usage: $MBS_INV extract <tarball-file>"
      echo
      echo "Recognized environment variables:"
      echo
      echo "  MBS_TARBALL_DIR   - Where to find the tarball if it is not in or"
      echo "                      relative to the current directory."
      echo "  MBS_EXTRACT_DEPTH - The parameter for '--strip-components' in"
      echo "                      tar. The default in $MBS_INV is 1, but tar"
      echo "                      itself would default to 0."
      echo
      echo "Notes:"
      echo
      echo "  $MBS_INV tries to find the 'bsdtar' program for extraction. If"
      echo "  this is not found, it instead tries to find the 'tar' program."
      echo "  If neither programs are found, $MBS_INV will exit on error."
      echo
      echo "  'bsdtar' (from libarchive) has inbuilt support for compressed"
      echo "  tarballs, and can also support many non-tar archive formats. By"
      echo "  contrast, 'tar' (GNU) only supports tarballs, and compressed"
      echo "  tarball support is dependent upon the relevant decompressor"
      echo "  being installed on the system. Keep this in mind when attempting"
      echo "  to extract non-tar archives and certain compressed tarballs."
      ;;
    apply)
      echo "Usage: $MBS_INV apply <patch-file>"
      echo
      echo "Recognized environment variables:"
      echo
      echo "  MBS_PATCH_DIR   - Where to find the patch file if it is not in"
      echo "                    or relative to the current directory."
      echo "  MBS_PATCH_DEPTH - The parameter for '-p' in patch. The default"
      echo "                    in $MBS_INV is 1, which is the most commonly"
      echo "                    patch depth. Should only be changed under rare"
      echo "                    circumstances, if you know you need a patch"
      echo "                    depth which differs from the default.."
      ;;
    configure)
      echo "Usage: $MBS_INV configure [optional additional parameters]"
      echo
      echo "Recognized environment variables:"
      echo
      echo "  MBS_CONFIGURE_RECONF - Set to 'YES' if 'autoreconf -fiv' should"
      echo "                         be run to (re)generate the configure"
      echo "                         script before configuring."
      echo "  MBS_FLAGS_CONFIGURE  - Replace the default flags to pass to"
      echo "                         configure, which are the following:"
      echo "                           --prefix=/usr \\"
      echo "                           --sysconfdir=/etc \\"
      echo "                           --localstatedir=/var \\"
      echo "                           --runstatedir=/run \\"
      echo "                           --bindir=/usr/bin \\"
      echo "                           --libdir=/usr/lib \\"
      echo "                           --sbindir=/usr/bin \\"
      echo "                           --infodir=/usr/share/info \\"
      echo "                           --mandir=/usr/share/man"
      echo
      echo "Notes:"
      echo
      echo "  $MBS_INV ONLY supports GNU Autotools-based configure scripts."
      echo "  It will run configure from (and hence, cause the Makefile to be"
      echo "  placed into) the '_mbsbuild' subdirectory of the source tree."
      echo "  '$MBS_INV build' detects this directory automatically (so you do"
      echo "  NOT need to 'cd' or 'pushd' into it after configure is done)."
      ;;
    meson)
      echo "Usage: $MBS_INV meson [optional additional parameters]"
      echo
      echo "Recognized environment variables:"
      echo
      echo "  MBS_MESON_BT    - The Meson build type ('--buildtype=')."
      echo "                    $MBS_INV will default to 'minsize' if unset."
      echo "                    See the Meson documentation for more options."
      echo "  MBS_FLAGS_MESON - Replace the default flags to pass to"
      echo "                    'meson setup', which are the following:"
      echo "                      --prefix=/usr \\"
      echo "                      --sysconfdir=/etc \\"
      echo "                      --localstatedir=/var \\"
      echo "                      --sbindir=bin \\"
      echo "                      --buildtype=\$MBS_MESON_BT"
      echo
      echo "Notes:"
      echo
      echo "  $MBS_INV will place the output of 'meson setup' into the"
      echo " '_mbsbuild' subdirectory of the source tree. '$MBS_INV build'"
      echo "  detects this directory automatically when subsequently run."
      ;;
    cmake)
      echo "Usage: $MBS_INV cmake [optional additional parameters]"
      echo
      echo "Recognized environment variables:"
      echo
      echo "  MBS_CMAKE_BT    - The CMake build type ('-DCMAKE_BUILD_TYPE')."
      echo "                    $MBS_INV will default to 'MinSizeRel' if"
      echo "                    unset. Commonly used build types include"
      echo "                    'Release', 'RelWithDebInfo', 'None'. See the"
      echo "                    CMake documentation for more information."
      echo "  MBS_FLAGS_CMAKE - Replace the default flags to pass to 'cmake',"
      echo "                    which are the following:"
      echo "                      -DCMAKE_INSTALL_PREFIX=/usr \\"
      echo "                      -DCMAKE_BUILD_TYPE=\$MBS_CMAKE_BT"
      echo
      echo "Notes:"
      echo
      echo "  $MBS_INV will place the output of 'cmake' into the '_mbsbuild'"
      echo "  subdirectory of the source tree. '$MBS_INV build' detects this"
      echo "  directory automatically when subsequently run."
      ;;
    build)
      echo "Usage: $MBS_INV build [optional additional parameters]"
      echo
      echo "Notes:"
      echo
      echo "  The subdirectory '_mbsbuild' is expected. $MBS_INV will detect"
      echo "  whether the build system uses a Makefile or Ninja automatically."
      echo "  Any optional additional parameters will be passed directly to"
      echo "  'make' or 'ninja', so only pass them if you know which build"
      echo "  system is in use (in most cases, they aren't needed anyway)."
      ;;
    install)
      echo "Usage: $MBS_INV install [optional additional parameters]"
      echo
      echo "Recognized environment variables:"
      echo
      echo "  DESTDIR                  - The path to use as the virtual root"
      echo "                             for the package installation. This"
      echo "                             creates a staged installation into a"
      echo "                             temporary directory, which could then"
      echo "                             be packaged or copied to '/' as"
      echo "                             desired."
      echo "  MBS_ALLOW_SYSINST        - Set to 'YES' to allow direct system"
      echo "                             installations if DESTDIR is unset."
      echo "                             This is NOT recommended for use on"
      echo "                             production systems."
      echo "  MBS_HUSH_SYSINST_WARNING - Set to 'YES' to surpress the warning"
      echo "                             emitted by $MBS_INV when performing a"
      echo "                             system installation (non-DESTDIR)."
      echo
      echo "Notes:"
      echo
      echo "  The subdirectory '_mbsbuild' is expected. $MBS_INV will detect"
      echo "  whether the build system uses a Makefile or Ninja automatically."
      echo "  Any optional additional parameters will be passed directly to"
      echo "  'make install' or 'ninja install', so only pass them if you know"
      echo "  which build system is in use (in most cases, they aren't needed"
      echo "  anyway). Makefile-based builds are always installed with '-j1'."
      ;;
    license)
      echo "Usage: $MBS_INV license <package-name> <license-file(s)>"
      echo
      echo "Recognized environment variables:"
      echo
      echo "  DESTDIR - The path to use as the virtual root for the license"
      echo "            file installation. It should match the DESTDIR set for"
      echo "            '$MBS_INV install'."
      echo
      echo "Notes:"
      echo
      echo "  License file(s) get installed under the directory"
      echo "  '/usr/share/licenses/<package-name>', prepended also by"
      echo "  \$DESTDIR if it is set."
      ;;
    cleanup)
      echo "Usage: $MBS_INV cleanup"
      echo
      echo "Recognized environment variables:"
      echo
      echo "  MBS_ALLOW_CLEANUP - If not set to 'YES' cleanup is not allowed."
      echo "                      Do NOT set this unless you know what you are"
      echo "                      doing, as it will remove everything from the"
      echo "                      current directory recursively, potentially"
      echo "                      causing data loss."
      ;;
    *)
      echo "$MBS_INV (MassOS Build System Utility) $MBS_VER (on $MBS_HOST_VER)"
      echo "Copyright (C) 2025 Daniel Massey / MassOS Developers"
      echo "Licensed under GNU GPLv3+; see '/usr/share/massos/LICENSE'."
      echo
      echo "Usage: $MBS_INV <command> [options]"
      echo
      echo "Available commands:"
      echo
      echo "  $MBS_INV extract   - Extract a source tarball."
      echo "  $MBS_INV apply     - Apply a patch file to the source tree."
      echo "  $MBS_INV configure - Configure a project using GNU Autotools."
      echo "  $MBS_INV meson     - Configure a project using Meson."
      echo "  $MBS_INV cmake     - Configure a project using CMake."
      echo "  $MBS_INV build     - Build a project after it is configured."
      echo "  $MBS_INV install   - Install a project after it has been built."
      echo "  $MBS_INV license   - Install one or more project license files."
      echo "  $MBS_INV cleanup   - Clean up the current directory."
      echo
      echo "For help with a specific command, use '$MBS_INV help <command>'."
      ;;
  esac
}

mbs_extract() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Set default extraction depth to 1 if unset.
  test ! -z "$MBS_EXTRACT_DEPTH" || MBS_EXTRACT_DEPTH=1
  # Locate file from current directory. Otherwise, check MBS_TARBALL_DIR.
  if test -z "$1"; then
    mbs_die "No tarball file name was specified."
  fi
  local tarball
  if test -e "$1"; then
    tarball="$1"
  elif test -e "$MBS_TARBALL_DIR/$1"; then
    tarball="$MBS_TARBALL_DIR/$1"
  else
    mbs_die "$1 was not found in the current directory or MBS_TARBALL_DIR."
  fi
  # Try to use bsdtar for extraction, since it supports more formats.
  local extractor
  if command -v bsdtar >/dev/null; then
    extractor=bsdtar
  elif command -v tar >/dev/null; then
    extractor=tar
  else
    mbs_die "No valid command for untarring was found on the system."
  fi
  # Extract the thing.
  mbs_msg "Extracting $tarball with $extractor"
  "$extractor" -xf "$tarball" --strip-components="$MBS_EXTRACT_DEPTH"
  if test $? -ne 0; then
    mbs_die "Failed to untar $tarball (MBS_EXTRACT_DEPTH=$MBS_EXTRACT_DEPTH)."
  fi
  # It's done.
  mbs_suc "Successfully untarred $tarball (MBS_EXTRACT_DEPTH=$MBS_EXTRACT_DEPTH)."
}

mbs_apply() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Look for the specified patch file relative to here, and MBS_PATCH_DIR.
  # Also look for .patch and .diff filename endings, if not explicitly set.
  if test -z "$1"; then
    mbs_die "No patch file name was specified."
  fi
  local patchfile
  if test -e "$1"; then
    patchfile="$1"
  elif test -e "$1.patch"; then
    patchfile="$1.patch"
  elif test -e "$1.diff"; then
    patchfile="$1.diff"
  elif test -e "$MBS_PATCH_DIR/$1"; then
    patchfile="$MBS_PATCH_DIR/$1"
  elif test -e "$MBS_PATCH_DIR/$1.patch"; then
    patchfile="$MBS_PATCH_DIR/$1.patch"
  elif test -e "$MBS_PATCH_DIR/$1.diff"; then
    patchfile="$MBS_PATCH_DIR/$1.diff"
  else
    mbs_die "$1 was not found in the current directory or MBS_PATCH_DIR."
  fi
  # Apply the patch with specified patch depth, or 1 if unset.
  test ! -z "$MBS_PATCH_DEPTH" || MBS_PATCH_DEPTH=1
  mbs_msg "Applying $patchfile with a patch depth of $MBS_PATCH_DEPTH."
  patch -Np"$MBS_PATCH_DEPTH" -i "$patchfile"
  if test $? -ne 0; then
    mbs_die "Failed to apply $patchfile (MBS_PATCH_DEPTH=$MBS_PATCH_DEPTH)."
  fi
  # It's done.
  mbs_suc "Successfully applied $patchfile (MBS_PATCH_DEPTH=$MBS_PATCH_DEPTH)."
}

mbs_configure() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Ensure the directory has a configure script.
  if test ! -x configure; then
    # Exit and report that the configure script was not found.
    mbs_die "No valid configure script was found."
  fi
  # Ensure the directory does not have leftovers from a previous build.
  if test -e _mbsbuild; then
    mbs_die "Existing build cache was found. Remove the _mbsbuild directory."
  fi
  # Run autoreconf if required.
  if test "$MBS_CONFIGURE_RECONF" = "YES"; then
    mbs_msg "Running autoreconf to regenerate the configure script..."
    autoreconf -fiv
    if test $? -ne 0; then
      mbs_die "Running autoreconf failed to regenerate the configure script."
    fi
  fi
  # Run the configure script.
  mbs_msg "Configuring the project with the configure script..."
  mkdir -p _mbsbuild; pushd _mbsbuild >/dev/null
  if test $? -ne 0; then
    mbs_die "$MBS_INV failed to create and change to _mbsbuild subdirectory."
  fi
  ../configure $MBS_FLAGS_CONFIGURE "$@"
  if test $? -ne 0; then
    popd >/dev/null
    mbs_die "The configure script failed to configure the project."
  fi
  popd >/dev/null
  # Ensure the configure script actually generated a Makefile.
  if test ! -f _mbsbuild/Makefile; then
    mbs_die "The configure script did not generate a Makefile."
  fi
  # It's done.
  mbs_suc "The project was successfully configured."
}

mbs_meson() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Ensure the directory has a meson.build file.
  if test ! -e meson.build; then
    mbs_die "No meson.build file exists in the current directory."
  fi
  # Ensure the directory does not have leftovers from a previous build.
  if test -e _mbsbuild; then
    mbs_die "Existing build cache was found. Remove the _mbsbuild directory."
  fi
  # Run the Meson build system.
  mbs_msg "Configuring the project with the Meson build system..."
  meson setup _mbsbuild $MBS_FLAGS_MESON "$@"
  if test $? -ne 0; then
    mbs_die "The Meson build system failed to configure the project."
  fi
  # It's done.
  mbs_suc "The project was successfully configured."
}

mbs_cmake() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Ensure the directory has a CMakeLists.txt file.
  if test ! -e CMakeLists.txt; then
    mbs_die "No CMakeLists.txt file exists in the current directory."
  fi
  # Ensure the directory does not have leftovers from a previous build.
  if test -e _mbsbuild; then
    mbs_die "Existing build cache was found. Remove the _mbsbuild directory."
  fi
  # Run the CMake build system.
  mbs_msg "Configuring the project with the CMake build system..."
  cmake $MBS_FLAGS_CMAKE "$@" -Wno-dev -G Ninja -B _mbsbuild -S .
  if test $? -ne 0; then
    mbs_die "The CMake build system failed to configure the project."
  fi
  # It's done.
  mbs_suc "The project was successfully configured."
}

mbs_build() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Ensure the _mbsbuild directory exists.
  if test ! -d _mbsbuild; then
    mbs_die "The project is not configured. Please configure it first."
  fi
  # Find a build file to indicate either Ninja or Make build should be used.
  local buildsystem
  if test -f _mbsbuild/build.ninja; then
    buildsystem="ninja"
  elif test -f _mbsbuild/Makefile; then
    buildsystem="make"
  else
    mbs_die "The project is not configured. Please configure it first."
  fi
  # Run the build system with any additional arguments needed.
  mbs_msg "Building the project using $buildsystem..."
  "$buildsystem" -C _mbsbuild "$@"
  if test $? -ne 0; then
    mbs_die "The project failed to be built using $buildsystem."
  fi
  # It's done.
  mbs_suc "The project was successfully built."
}

mbs_install() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Cannot run this if we are not root or DESTDIR is not set.
  if test -z "$DESTDIR" && test $EUID -ne 0; then
    mbs_die "Installing a project without DESTDIR requires root access."
  fi
  # Cannot install without DESTDIR if we are not the MassOS build system.
  if test -z "$DESTDIR" && test "$MBS_ALLOW_SYSINST" != "YES"; then
    mbs_die "Installing a project requires DESTDIR (or MBS_ALLOW_SYSINST=YES)."
  fi
  # Warn user if MBS_ALLOW_SYSINST=YES without MBS_HUSH_SYSINST_WARNING=YES.
  if test -z "$DESTDIR" && test "$MBS_HUSH_SYSINST_WARNING" != "YES"; then
    mbs_msg "WARNING! ALLOWING SYSTEM INSTALLATIONS MAY BREAK YOUR SYSTEM!"
  fi
  # Do not proceed if the _mbsbuild directory does not exist.
  if test ! -d _mbsbuild; then
    mbs_die "Project is not configured. Please configure and build it first."
  fi
  # Find a build file to indicate either Ninja or Make build should be used.
  local buildsystem
  if test -f _mbsbuild/build.ninja; then
    buildsystem="ninja"
  elif test -f _mbsbuild/Makefile; then
    buildsystem="make"
  else
    mbs_die "Project is not configured. Please configure and build it first."
  fi
  # Makefile needs DESTDIR passed as an argument, not as environment variable.
  local installparams=""
  if test "$buildsystem" = "make"; then
    installparams="-j1 DESTDIR=$DESTDIR"
  fi
  installparams+="$@"
  # Run the build system to install with any additional arguments needed.
  mbs_msg "Installing the project using $buildsystem..."
  "$buildsystem" -C _mbsbuild install $installparams
  if test $? -ne 0; then
    mbs_die "The project failed to install using $buildsystem."
  fi
  # Finishing message.
  mbs_suc "The project was successfully installed."
}

mbs_license() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Cannot run this if we are not root or DESTDIR is not set.
  if test -z "$DESTDIR" && test $EUID -ne 0; then
    mbs_die "Installing license files without DESTDIR requires root access."
  fi
  # Capture package name and shift arguments.
  local licpkg="$(echo "$1" | tr '[:upper:]' '[:lower:]')"
  shift
  # Ensure the package name was specified.
  if test -z "$licpkg"; then
    mbs_die "You must specify the package name to install licenses for."
  fi
  # Ensure at least one license file was specified.
  if test -z "$*"; then
    mbs_die "You must specify at least one license file to install."
  fi
  # Ensure all the files are not not specified.
  for lic in "$@"; do
    if test ! -f "$lic"; then
      mbs_die "License file $lic does not exist."
    fi
  done
  # Install all license files.
  mbs_msg "Installing license files to $DESTDIR/usr/share/licenses/$licpkg..."
  install -vt "$DESTDIR"/usr/share/licenses/"$licpkg" -Dm644 "$@"
  if test $? -ne 0; then
    mbs_die "The license files failed to be installed successfully."
  fi
  # Finishing message.
  mbs_suc "The license files were successfully installed."
}

mbs_cleanup() {
  # Welcome message.
  mbs_msg "Working in directory $PWD."
  # Do not run if we are in a dangerous directory.
  # Also require MBS_ALLOW_CLEANUP to be set.
  # This is for safety, since it will remove all files recursively.
  if test "$PWD" = "$HOME" || test "$PWD" = "/root" || test "$PWD" = "/"; then
    mbs_msg "WARNING! ALL FILES FROM CURRENT DIRECTORY WILL BE DELETED!"
    mbs_die "For safety, cleanup is not allowed in $PWD."
  fi
  if test "$MBS_ALLOW_CLEANUP" != "YES"; then
    mbs_msg "WARNING! ALL FILES FROM CURRENT DIRECTORY WILL BE DELETED!"
    mbs_die "For safety, cleanup is not allowed unless MBS_ALLOW_CLEANUP=YES."
  fi
  # Remove everything from the current directory.
  mbs_msg "Cleaning up the directory..."
  find . -mindepth 1 -delete
  mbs_suc "The directory was successfully cleaned up."
}

# Capture chosen command and shift arguments.
MBS_COMMAND="$(echo "$1" | tr '[:upper:]' '[:lower:]')"
shift

# Check how the program is run.
case "$MBS_COMMAND" in
  extract) mbs_extract "$@" ;;
  apply) mbs_apply "$@" ;;
  configure) mbs_configure "$@" ;;
  meson) mbs_meson "$@" ;;
  cmake) mbs_cmake "$@" ;;
  build) mbs_build "$@" ;;
  install) mbs_install "$@" ;;
  license) mbs_license "$@" ;;
  cleanup) mbs_cleanup "$@" ;;
  help|h|-h|-help|--help) mbs_usage "$@" ;;
  version|v|-v|-version|--version) mbs_usage | head -n3 ;;
  *) mbs_usage >&2; exit 1 ;;
esac
