#!/bin/bash
#
# Wrapper around 'dracut', which can be used to generate an initramfs.
# Copyright (C) 2021 The Sonic Master.
#
# Exit on error.
set -e
# Ensure we are running as root.
if [ $EUID -ne 0 ]; then
  echo "Error: $(basename $0) must be run as root." >&2
  exit 1
fi
# Usage function.
usage() {
  echo "Usage: $(basename $0) [kernel-version]"
  echo
  echo "$(basename $0) generates an initramfs for you."
  echo
  echo "If [kernel-version] is omitted, $(basename $0) tries to generate an"
  echo "initramfs for the currently running kernel, instead of a specific one."
  echo "Note that this will fail in a chroot environment, so [kernel-version]"
  echo "must not be omitted if running in a chroot."
}
# Try to generate for the currently running kernel if $1 is omitted.
if [ -z "$1" ]; then
  KVER="$(uname -r)"
  if [ ! -d "/lib/modules/$KVER" ]; then
    echo "Error: Kernel version not provided and current kernel not valid." >&2
    echo
    usage >&2
    exit 1
  fi
else
  KVER="$1"
  if [ ! -d "/lib/modules/$KVER" ]; then
    echo "Error: Specified kernel version $KVER does not exist." >&2
    exit 1
  fi
fi
# Generate the initramfs.
printf "Generating an initramfs for kernel $KVER... "
dracut -q --force "/boot/initramfs-$KVER.img" "$KVER"
echo "Done!"
