#!/bin/bash
#
# Script to generate locales specified in '/etc/locales'.
#
# Exit on error.
set -e
# Ensure we are running as root.
if [ $EUID != 0 ]; then
  echo "Error: $0 must be run as root." >&2
  exit 1
fi

if [ ! -e /etc/locales ]; then
  echo "Error: The file /etc/locales does not exist." >&2
  exit 1
fi

# Locale generation function.
gen_locale() {
  printf "Generating locale $1.$2... "
  localedef -i $1 -c -f $2 -A /usr/share/locale/locale.alias $3
  echo "Done!"
}

# Remove old locale data before generating.
rm -rf /usr/lib/locale/locale-archive

# Generate C.UTF-8 first.
gen_locale C UTF-8 C.UTF-8

# Now generate locales listed in /etc/locales.
while read locale charset; do
  case $locale in
    \#*|"") continue ;;
  esac
  real_locale="$(echo $locale | cut -d. -f1)"
  if [ -z "$locale" ] || [ -z "$charset" ]; then
    continue
  fi
  gen_locale $real_locale $charset $locale
done < /etc/locales

# Finishing message.
echo "Locales successfully generated."
